### ISSUE TITLE
[Android] App gets crashed on startDeamon call

### ISSUE THREAD

**Issue by seland** [Bit-Nation/react-native-eth-daemon#11]
## Issue description

React Native app call startDaemon using this code:
```
import daemon from 'react-native-eth-daemon';

daemon.startDaemon({
        enabledEthereum:true,
        networkID: 3,
        enodesNumber:16,
        maxPeers:25,
        enabledWhisper:false
    }
```

App gets crashed with error:
```
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 6364 (mqt_native_modu)

        [ 01-12 19:11:39.501  1262: 1262 W/         ]
        debuggerd: handling request: pid=5943 uid=10091 gid=10091 tid=6364
```

Debugging shows that crash happens in that [line](https://github.com/Bit-Nation/react-native-eth-daemon/blob/development/android/app/src/main/java/com/reactlibrary/RNEthDaemonModule.java#L40).

## Expected behavior

App loads correctly without crash.

**Comment by albertoestarrona** [comment]
This unexpected crash happens only with some Android simulator configurations. On real devices runs with no problem.

This it's because the simulator can have different resources configs (made by the user) and in some cases the local resources are not enough to fulfill React-Native and Geth needs.
