### ISSUE TITLE
no suitable peers available

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/react-native-eth-daemon#12]
Hi, 

I am getting an `Failed to retrieve data from network     err="no suitable peers available"` error. 
I think it's related to the bootstrapping nodes. See [here](https://github.com/ethereum/mist/issues/3393) and [here](https://ethereum.stackexchange.com/questions/11014/how-to-run-a-server-for-light-clients). Shortversion: light mode is still an experimental feature. You need special peer's that allow that feature (it must be enabled).

**Comment by albertoestarrona** [comment]
This should be solved with Feature/updated libs #13
