### ISSUE TITLE
[daemon] start / stop methods

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/react-native-eth-daemon#2]
## Feature
Since a user need's to connect to ethereum we need a start / stop functionality for the ethereum daemon. 

## Acceptance Criteria
- [x] `startDaemon` on ios
- [x] `startDaemon` on android
- [x] `stopDaemon` on ios
- [x] `stopDaemon` on android
- [x] Javascript bridge
- [x] JSON-RPC is started on localhost.
- [x] Config should be passed to the start method as an json object

**Comment by albertoestarrona** [comment]
Ready now with all the criteria checked
