### ISSUE TITLE
promise resolve / rejection

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/react-native-eth-daemon#8]
Hi,

some small canges about the resolve / reject of start / stop daemon.

[Here](https://github.com/Bit-Nation/react-native-eth-daemon/blob/development/ios/RNEthDaemon.m#L55) and [here](https://github.com/Bit-Nation/react-native-eth-daemon/blob/development/ios/RNEthDaemon.m#L69) it makes more sense to resolve the promise with "null" or "void". There is no need for a text message because a promise will never be resolved when there is an error. 

I am not able to get the original geth error message [here](https://github.com/Bit-Nation/react-native-eth-daemon/blob/development/ios/RNEthDaemon.m#L71) and [here](https://github.com/Bit-Nation/react-native-eth-daemon/blob/development/ios/RNEthDaemon.m#L57) when the promise is rejected. I only see the text message which isn't really helpful since it don't provide information about the error. Can you change it to reject with the error from the geth lib? I attach an screenshot of what I mean:
<img width="564" alt="bildschirmfoto 2017-12-30 um 11 51 42" src="https://user-images.githubusercontent.com/16626192/34453542-eca55c9c-ed57-11e7-8e82-92a6878b76dd.png">

**Comment by albertoestarrona** [comment]
Ready for both iOS/Android
